# http://localhost:4000/DHMakesMethodz/
# to view locally
title: '#DHmakes Methodz Talks'
baseurl: /DHMakesMethodz
url: "https://amandavisconti.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed